language:
  - cpp

sudo:
  - required

dist:
  - trusty

install:
  - export PATH=/usr/bin:$PATH # use Python from /usr/bin/ instead of /opt/python

  - sudo apt-get install python-pip

  - which python
  - python --version

  - which pip
  - pip --version

  - sudo pip install 'requests[security]'
  - sudo pip install ansible

script:
  # Fix layout
  - cd ..
  - mv ansible-opendronemap opendronemap
  - cd opendronemap

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run local test (first build will take a long time)
  - ansible-playbook -vvv tests/test.yml -i tests/inventory --connection=local

  # Run again (should be fast)
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
