language:
  - python

python:
  - "2.7"

sudo:
  - required

dist:
  - trusty

install:
  - sudo pip install 'requests[security]'
  - sudo pip install ansible

script:
  # Fix layout
  - cd ..
  - mv ansible-opendronemap opendronemap
  - cd opendronemap

  - python --version

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run local test (first build will take a long time)
  - ansible-playbook -vvv tests/test.yml -i tests/inventory --connection=local

  # Run again (should be fast)
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
